"""empty message

Revision ID: 2bcd756c72c4
Revises: 8225c39a2292
Create Date: 2022-04-09 13:09:45.294336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bcd756c72c4'
down_revision = '8225c39a2292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hospital', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hospital')
    # ### end Alembic commands ###
