"""empty message

Revision ID: 63a989175c40
Revises: 2bcd756c72c4
Create Date: 2022-04-09 13:12:00.869947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a989175c40'
down_revision = '2bcd756c72c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hospital', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hospital')
    # ### end Alembic commands ###
