"""empty message

Revision ID: 6e60469d6a98
Revises: aa0f5c26a551
Create Date: 2022-04-09 08:48:02.115133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e60469d6a98'
down_revision = 'aa0f5c26a551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contribution_frequency', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contribution_frequency')
    # ### end Alembic commands ###
