"""empty message

Revision ID: aa0f5c26a551
Revises: d475c18c3fbf
Create Date: 2022-04-09 02:11:45.919843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0f5c26a551'
down_revision = 'd475c18c3fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contribution_frequency', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contribution_frequency')
    # ### end Alembic commands ###
